kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcptest
spec:
  replicas: 1
  template:
    metadata:
      name: gcptest
      labels:
        app: gcptest
    spec:
      containers:
        - name: gcptest
          image: gcr.io/macs-engineering/gcptest@sha256:a645e1d595a19b6a32ecb73b9189086d07a53cae20e8044c439b76df688dd55b
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
