kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcptest
spec:
  replicas: 1
  template:
    metadata:
      name: gcptest
      labels:
        app: gcptest
    spec:
      containers:
        - name: gcptest
          image: gcr.io/macs-engineering/gcptest@sha256:55397aa29ca5160cea9cc5f0a30c64cb4d60bd820482e98718cbb8f0a2e47820
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
