kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcptest
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: gcptest
      labels:
        app: gcptest
    spec:
      containers:
      - name: gcptest
        image: gcr.io/macs-engineering/gcptest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: gcp-service
  name: gcp-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gcptest
  sessionAffinity: None
  type: LoadBalancer